### ISSUE TITLE
1.0.0dev5 release

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/text_formatter#32]
This is the tracking issue for version `1.0.0dev5` of **text\_formatter**.

## Release process jobs:

- [x] Make GitHub release and tag
- [ ] Upload package to http://pypi.org/project/text_formatter
- [ ] Make note on project [`text_formatter - Project board`](https://github.com/users/DiddiLeija/projects/4#column-14845989)

**Comment by DiddiLeija** [comment]
I don't know if we must release this. Even when most of our issues are closed, we are not ready for a consistent release at all.

**Comment by DiddiLeija** [comment]
There are just a lot of things to do. I'll cancel this process.
